### PR TITLE
Supports GHC 7.8.3 and cabal sandboxes

### PR DESCRIPTION
**Pull request by schell**
Includes updates for GHC 7.8.3 and cabal support from @maximkulkin's https://github.com/maximkulkin/hdevtools/tree/cabal-support

### CODE REVIEW

**Comment by real-or-random** [comment]
The handling of subdirectories does not really work for me:

Assume the current folder contains .cabal file and .cabal-sandbox directory.
``` > hdevtools check src/Vektz/Frontend/Test.hs``` works fine. However, in a subdir, the cabal sandbox is not respected:
```
 > cd src
 > hdevtools check Vektz/Frontend/Test.hs
Vektz/Backend/Colors.hs:6:8:
    Could not find module ‘Data.Colour.SRGB’
    Use -v to see a list of the files searched for.
[...]
```
Any ideas?

**Comment by schell** [comment]
@real-or-random - hmmm. I think the only way for hdevtools to respect a cabal file in parent directories is for it to look for the cabal file recursively up the filesystem. I can imagine that someone may have a .cabal somewhere in a parent directory while working on a project without a cabal file, which would cause a bit of a mix up. Do you think that case is rare enough not to worry about?

**Comment by maximkulkin** [comment]
@schell Actually, support for searching cabal file was added with 0ee6a4105983d03a177bcc36e99a8c95d42d157d and 0f37a154b46ffe21bd9c3aae8944b5dc01400bf3. So, it need to be further investigated: 1) make sure that this patch was applied; 2) what is the project's directory/file layout?

**Comment by real-or-random** [comment]
It's the current hdevtools-0.1.0.6 from hackage; I did a clean re-install to verify.

The layout is pretty standard:
The base dir contains the files ```vektz.cabal```, ```cabal.sandbox.config``` and the directories ```.cabal-sandbox```, ```dist```, and ```src```. Then, ```src``` contains the modules.

**Comment by schell** [comment]
@maximkulkin the patch is applied - https://github.com/schell/hdevtools/commits/master

**Pull request closed without merging**
